deploy:
  provider: pypi
  user: drumperl
  password:
    secure: XUbJUSR98CIPPb5oXpE0hsRG6qs/LgX+3u1EgL8YcA5AbYfihOf7DfZlS1S0XfQOO9xlOeRM4YvQk8ZPq7P4T+nWHH0hIn2oiLd1mM+ZJA3Pp5Aoa19xPzGwm2nUYYG7GafxwpqaJxOh7ydtMjZr1iWgoIh84Tsm6UcLZ1kJE3OqUtuSyXzpg/ukfMbYx3ChQDVj/cBg9+SBND+W9IJGf6vjXVRMLhtMCYDDsIltLZ1o/h/9u5jw6v2kjm+zKu1r4kjHrLrcEg+fAAyAcBS/eUsETByKASV5+5yClN232VAdmL8IKzXUeW7RFuhpVtyIXCy8MGvVFIFA0PUrcyiAmwYxPoaeZRxgpWK/h8sUPqtKYhoL9FjvVdks0o851D1hIFlAZQU6MGwBmlBFQEHylsgTrF1QEY479B2Fa0VlPUo8tv2puRfc4HrKAh6RFRpYF1hajsrV2gKr4yqCnh6uS0wo+XXWWQDus1PHjatOMVeOs59WNSHMpa9s+kN7D80PQArKnB1Mw3nQi5PTeKdaTypkKPtE/6myc4E9sdevVwYrU9tGBJXF6a95SiKqzYpvCjHuFDPbhpwdTuNY+pIeouB9XQihDd/J2ZGI791gU6pCenhV1nNKhXIhnTo9jy8jOtejZ4DiSf2wAdnhWqTUXtvVB6XVSugZesdh2jZMFYQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rjoyal/domain_shared_contacts_client
env:
- TOXENV=py27
- TOXENV=pypy
install: pip install -U tox
language: python
python: 2.7
script: tox -e ${TOXENV}
